import { AssetCollectionMetaData } from "../assets/types";

export const stockFootageMetaData: AssetCollectionMetaData[] = [
	{
		title: "Afghanistan",
		thumbnail: "afghanmain.jpg",
		hostedLink: "afghanistan",
		assetItemMetaData: [
			{
				title: "Complete Afghanistan Collection (21 Clips)",
				price: 39,
				thumbnail: "afghanistan/afghanmain.jpg",
				link: "https://franklinvmoon.gumroad.com/l/kraynl",
				created: 1750143316,
				tags: [""],
				isPack: true,
			},
			{
				title: "Balkh Green Mosque",
				price: 5,
				thumbnail: "afghanistan/Balkh_Green_Mosque.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/svddx",
				created: 1750143317,
				tags: [""],
			},
			{
				title: "Balkh Walls",
				price: 5,
				thumbnail: "afghanistan/Balkh_Walls_1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/fnnoi",
				created: 1750143075,
				tags: [""],
			},
			{
				title: "Balkh Walls 2",
				price: 5,
				thumbnail: "afghanistan/Balkh_Walls_2.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/tksrr",
				created: 1750143032,
				tags: [""],
			},
			{
				title: "Bamyan Band-e-Amir",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Band-e-Amir.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/pcyrhh",
				created: 1750143151,
				tags: [""],
			},
			{
				title: "Bamyan Buddha",
				price: 15,
				thumbnail: "afghanistan/Bamyan_Buddha_1.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/cyuwc",
				created: 1750143260,
				tags: [""],
			},
			{
				title: "Bamyan Buddha 2",
				price: 15,
				thumbnail: "afghanistan/Bamyan_Buddha_2.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/osmult",
				created: 1750143197,
				tags: [""],
			},
			{
				title: "Bamyan Gholghola City",
				price: 10,
				thumbnail: "afghanistan/Bamyan_Gholghola_City.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/cmudi",
				created: 1750143301,
				tags: [""],
			},
			{
				title: "Bamyan Shahr-e-Zohak",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Shahr-e-Zohak.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/vqlzi",
				created: 1750143636,
				tags: [""],
			},
			{
				title: "Herat Citadel",
				price: 5,
				thumbnail: "afghanistan/Herat_Citadel_1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/uemeo",
				created: 1750143337,
				tags: [""],
			},
			{
				title: "Herat Citadel 2",
				price: 5,
				thumbnail: "afghanistan/Herat_Citadel_2.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/bjaii",
				created: 1750143460,
				tags: [""],
			},
			{
				title: "Herat Citadel 3",
				price: 10,
				thumbnail: "afghanistan/Herat_Citadel_3.jpg",
				length: 2,
				link: "https://franklinvmoon.gumroad.com/l/zvmyl",
				created: 1750143588,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum",
				price: 5,
				thumbnail: "afghanistan/Herat_Gawhar_Shad_Mausoleum_1.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/rwgsw",
				created: 1750143121,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum 2",
				price: 5,
				thumbnail: "afghanistan/Herat_Gawhar_Shad_Mausoleum_2.jpg",
				length: 7,
				link: "https://franklinvmoon.gumroad.com/l/jtvze",
				created: 1750143060,
				tags: [""],
			},
			{
				title: "Herat Khwaja Abdullah Ansari Shrine",
				price: 10,
				thumbnail: "afghanistan/Herat_Khwaja_Abdullah_Ansari_Shrine.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/uovkc",
				created: 1750143007,
				tags: [""],
			},
			{
				title: "Kabul Park",
				price: 5,
				thumbnail: "afghanistan/Kabul_Park.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/rtzyx",
				created: 1750143478,
				tags: [""],
			},
			{
				title: "Kabul Roundabout",
				price: 5,
				thumbnail: "afghanistan/Kabul_Roundabout.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/jwxnd",
				created: 1750143613,
				tags: [""],
			},
			{
				title: "Kabul Walls",
				price: 5,
				thumbnail: "afghanistan/Kabul_Walls.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/pwlqe",
				created: 1750142955,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_1.jpg",
				length: 18,
				link: "https://franklinvmoon.gumroad.com/l/efmzeu",
				created: 1750143574,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 2",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_2.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/flzob",
				created: 1750143374,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 3",
				price: 10,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_3.jpg",
				length: 11,
				link: "https://franklinvmoon.gumroad.com/l/zzdipq",
				created: 1750143442,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Hazrat Ali",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif_Hazrat_Ali.jpg",
				length: 9,
				link: "https://franklinvmoon.gumroad.com/l/qyoaoy",
				created: 1750143235,
				tags: [""],
			},
		],
		wallpapers: [
			"afghanistan_mazar-e-sharif_blue_mosque.jpg",
			"afghanistan_kabul_slums.jpg",
			"afghanistan_shot_humvee_mosque.jpg",
			"afghanistan_herat_mosque.jpg",
			"afghanistan_kabul_street.jpg",
			"afghanistan_snow.jpg",
			"afghanistan_bamyan_snow.jpg",
			"afghanistan_bamyan_buddha_hole.jpg",
			"afghanistan_bamyan_buddhas.jpg",
			"afghanistan_herat_mosque_2.jpg",
			"afghanistan_snowing.jpg",
			"afghanistan_horse_brawl.jpg",
			"afghanistan_baulk_walls.jpg",
			"afghanistan_TB_flag.jpg",
		],
	},
	{
		title: "Bhutan",
		thumbnail: "bhutanmain.jpg",
		hostedLink: "bhutan",
		assetItemMetaData: [
			{
				title: "Complete Bhutan Collection (9 Clips)",
				price: 24,
				thumbnail: "bhutan/bhutanmain.jpg",
				link: "https://franklinvmoon.gumroad.com/l/kbcmo",
				created: 1759855315,
				tags: [""],
				isPack: true,
			},
			{
				title: "Bhutan Bridge",
				price: 5,
				thumbnail: "bhutan/bhutan_bridge.jpg",
				length: 20,
				link: "https://franklinvmoon.gumroad.com/l/ujiaah",
				created: 1759855316,
				tags: [""],
			},
			{
				title: "Bhutan Dog 1",
				price: 5,
				thumbnail: "bhutan/bhutan_dog_1.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/nwlrkl",
				created: 1759855402,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 1",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_1.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/ymgsm",
				created: 1759855744,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 2",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_2.jpg",
				length: 9,
				link: "https://franklinvmoon.gumroad.com/l/fswpq",
				created: 1759855701,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 3",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_3.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/ylhdot",
				created: 1759855579,
				tags: [""],
			},
			{
				title: "Bhutan Flag",
				price: 5,
				thumbnail: "bhutan/bhutan_flag.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/afvuoi",
				created: 1759855354,
				tags: [""],
			},
			{
				title: "Bhutan Prayer Flags",
				price: 5,
				thumbnail: "bhutan/bhutan_prayer_flags.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/shkouy",
				created: 1759855633,
				tags: [""],
			},
			{
				title: "Bhutan Tigers Nest",
				price: 5,
				thumbnail: "bhutan/bhutan_tigers_nest.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/hdiutb",
				created: 1759855427,
				tags: [""],
			},
			{
				title: "Bhutan Traffic Director",
				price: 5,
				thumbnail: "bhutan/bhutan_traffic_director.jpg",
				length: 17,
				link: "https://franklinvmoon.gumroad.com/l/bdxif",
				created: 1759855544,
				tags: [""],
			},
		],
		wallpapers: [
			"bhutan_sunset.jpg",
			"bhutan_monastery.jpg",
			"bhutan_prayer_flags_better.jpg",
			"bhutan_admin.jpg",
			"bhutan_family_home.jpg",
			"bhutan_thimphu.jpg",
			"bhutan_tigers_nest_enhanced.jpg",
		],
	},
	// {
	// 	title: "Iran",
	// 	thumbnail: "iranmain.jpg",
	// 	hostedLink: "iran",
	// 	assetItemMetaData: [],
	// 	wallpapers: [],
	// },
	// {
	// 	title: "Syria (Assad)",
	// 	thumbnail: "syriamain.jpg",
	// 	hostedLink: "syria",
	// 	assetItemMetaData: [],
	// 	wallpapers: [],
	// },
];
