import { AssetCollectionMetaData } from "../assets/types";

export const stockFootageMetaData: AssetCollectionMetaData[] = [
	{
		title: "Syria (Assad era)",
		thumbnail: "syriamain.jpg",
		hostedLink: "syria",
		assetItemMetaData: [
			{
				title: "Aleppo Ruins",
				price: 5,
				thumbnail: "syria/Aleppo_Ruins.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/mwvom",
				created: 1760978157,
				tags: [""],
			},
			{
				title: "Aleppo Ruins 2",
				price: 5,
				thumbnail: "syria/Aleppo_Ruins_2.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/yksrm",
				created: 1760977890,
				tags: [""],
			},
			{
				title: "Busra Ruins",
				price: 5,
				thumbnail: "syria/Busra_Ruins.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/vftirp",
				created: 1760978009,
				tags: [""],
			},
			{
				title: "Damascus Ruins",
				price: 5,
				thumbnail: "syria/Damascus_Ruins.jpg",
				length: 7,
				link: "https://franklinvmoon.gumroad.com/l/scnod",
				created: 1760977824,
				tags: [""],
			},
			{
				title: "Damascus Flag Garages",
				price: 5,
				thumbnail: "syria/Damascus_Assad_Flag_Garages.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/shhjis",
				created: 1760978111,
				tags: [""],
			},
			{
				title: "Hama Wheel",
				price: 5,
				thumbnail: "syria/Hama_Wheel.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/ptrxgn",
				created: 1760977851,
				tags: [""],
			},
			{
				title: "Homs Ruins",
				price: 5,
				thumbnail: "syria/Homs_Ruins.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/xwurx",
				created: 1760977980,
				tags: [""],
			},
			{
				title: "Marmarita Festival",
				price: 5,
				thumbnail: "syria/Marmarita_Festival.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/rjmgf",
				created: 1760977785,
				tags: [""],
			},
			{
				title: "Palmyra Bel Temple",
				price: 5,
				thumbnail: "syria/Palmyra_Bel_Temple.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/cvapb",
				created: 1760978060,
				tags: [""],
			},
			{
				title: "Soap Factory",
				price: 5,
				thumbnail: "syria/Soap_Factory.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/haemt",
				created: 1760977734,
				tags: [""],
			},
			{
				title: "Syria Old Flag",
				price: 5,
				thumbnail: "syria/Syria_Flag_Assad.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/mdzmn",
				created: 1760978035,
				tags: [""],
			},
			{
				title: "Umayyad Mosque",
				price: 5,
				thumbnail: "syria/Umayyad_Mosque.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/xvjip",
				created: 1760977954,
				tags: [""],
			},
			{
				title: "Complete Syria Collection (12 Clips)",
				price: 20,
				thumbnail: "syria/Syria_damascus_sword.jpg",
				link: "https://franklinvmoon.gumroad.com/l/mrqpli",
				created: 1760977955,
				tags: [""],
				isPack: true,
			},
		],
		wallpapers: [
			"Busra_Ampitheatre.jpg",
			"Busra_Ruins.jpg",
			"Damascus_Assad_Era_Flags.jpg",
			"Free_Syria_Rebel_Graffiti.jpg",
			"Hama_Wheel.jpg",
			"Homa_Ruins.jpg",
			"Maaloula.jpg",
			"Russian_Transport_Syria.jpg",
			"Sign_Iraq_Damascus.jpg",
			"Syria_Castle.jpg",
			"Syria_Flag.jpg",
			"Umayyad_Square.jpg",
		],
	},
	{
		title: "Bhutan",
		thumbnail: "bhutanmain.jpg",
		hostedLink: "bhutan",
		assetItemMetaData: [
			{
				title: "Bhutan Bridge",
				price: 5,
				thumbnail: "bhutan/bhutan_bridge.jpg",
				length: 20,
				link: "https://franklinvmoon.gumroad.com/l/ujiaah",
				created: 1759855316,
				tags: [""],
			},
			{
				title: "Bhutan Dog 1",
				price: 5,
				thumbnail: "bhutan/bhutan_dog_1.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/nwlrkl",
				created: 1759855402,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 1",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_1.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/ymgsm",
				created: 1759855744,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 2",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_2.jpg",
				length: 9,
				link: "https://franklinvmoon.gumroad.com/l/fswpq",
				created: 1759855701,
				tags: [""],
			},
			{
				title: "Bhutan Dzhong 3",
				price: 5,
				thumbnail: "bhutan/bhutan_dzhong_3.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/ylhdot",
				created: 1759855579,
				tags: [""],
			},
			{
				title: "Bhutan Flag",
				price: 5,
				thumbnail: "bhutan/bhutan_flag.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/afvuoi",
				created: 1759855354,
				tags: [""],
			},
			{
				title: "Bhutan Prayer Flags",
				price: 5,
				thumbnail: "bhutan/bhutan_prayer_flags.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/shkouy",
				created: 1759855633,
				tags: [""],
			},
			{
				title: "Bhutan Tigers Nest",
				price: 5,
				thumbnail: "bhutan/bhutan_tigers_nest.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/hdiutb",
				created: 1759855427,
				tags: [""],
			},
			{
				title: "Bhutan Traffic Director",
				price: 5,
				thumbnail: "bhutan/bhutan_traffic_director.jpg",
				length: 17,
				link: "https://franklinvmoon.gumroad.com/l/bdxif",
				created: 1759855544,
				tags: [""],
			},
			{
				title: "Complete Bhutan Collection (9 Clips)",
				price: 20,
				thumbnail: "bhutan/bhutanmain.jpg",
				link: "https://franklinvmoon.gumroad.com/l/kbcmo",
				created: 1759855315,
				tags: [""],
				isPack: true,
			},
		],
		wallpapers: [
			"bhutan_sunset.jpg",
			"bhutan_monastery.jpg",
			"bhutan_prayer_flags_better.jpg",
			"bhutan_admin.jpg",
			"bhutan_family_home.jpg",
			"bhutan_thimphu.jpg",
			"bhutan_tigers_nest_enhanced.jpg",
		],
	},

	{
		title: "Afghanistan",
		thumbnail: "afghanmain.jpg",
		hostedLink: "afghanistan",
		assetItemMetaData: [
			{
				title: "Balkh Green Mosque",
				price: 5,
				thumbnail: "afghanistan/Balkh_Green_Mosque.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/svddx",
				created: 1750143317,
				tags: [""],
			},
			{
				title: "Balkh Walls",
				price: 5,
				thumbnail: "afghanistan/Balkh_Walls_1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/fnnoi",
				created: 1750143075,
				tags: [""],
			},
			{
				title: "Balkh Walls 2",
				price: 5,
				thumbnail: "afghanistan/Balkh_Walls_2.jpg",
				length: 4,
				link: "https://franklinvmoon.gumroad.com/l/tksrr",
				created: 1750143032,
				tags: [""],
			},
			{
				title: "Bamyan Band-e-Amir",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Band-e-Amir.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/pcyrhh",
				created: 1750143151,
				tags: [""],
			},
			{
				title: "Bamyan Buddha",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Buddha_1.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/cyuwc",
				created: 1750143260,
				tags: [""],
			},
			{
				title: "Bamyan Buddha 2",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Buddha_2.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/osmult",
				created: 1750143197,
				tags: [""],
			},
			{
				title: "Bamyan Gholghola City",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Gholghola_City.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/cmudi",
				created: 1750143301,
				tags: [""],
			},
			{
				title: "Bamyan Shahr-e-Zohak",
				price: 5,
				thumbnail: "afghanistan/Bamyan_Shahr-e-Zohak.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/vqlzi",
				created: 1750143636,
				tags: [""],
			},
			{
				title: "Herat Citadel",
				price: 5,
				thumbnail: "afghanistan/Herat_Citadel_1.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/uemeo",
				created: 1750143337,
				tags: [""],
			},
			{
				title: "Herat Citadel 2",
				price: 5,
				thumbnail: "afghanistan/Herat_Citadel_2.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/bjaii",
				created: 1750143460,
				tags: [""],
			},
			{
				title: "Herat Citadel 3",
				price: 5,
				thumbnail: "afghanistan/Herat_Citadel_3.jpg",
				length: 2,
				link: "https://franklinvmoon.gumroad.com/l/zvmyl",
				created: 1750143588,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum",
				price: 5,
				thumbnail: "afghanistan/Herat_Gawhar_Shad_Mausoleum_1.jpg",
				length: 10,
				link: "https://franklinvmoon.gumroad.com/l/rwgsw",
				created: 1750143121,
				tags: [""],
			},
			{
				title: "Herat Gawhar Shad Mausoleum 2",
				price: 5,
				thumbnail: "afghanistan/Herat_Gawhar_Shad_Mausoleum_2.jpg",
				length: 7,
				link: "https://franklinvmoon.gumroad.com/l/jtvze",
				created: 1750143060,
				tags: [""],
			},
			{
				title: "Herat Khwaja Abdullah Ansari Shrine",
				price: 5,
				thumbnail: "afghanistan/Herat_Khwaja_Abdullah_Ansari_Shrine.jpg",
				length: 12,
				link: "https://franklinvmoon.gumroad.com/l/uovkc",
				created: 1750143007,
				tags: [""],
			},
			{
				title: "Kabul Park",
				price: 5,
				thumbnail: "afghanistan/Kabul_Park.jpg",
				length: 3,
				link: "https://franklinvmoon.gumroad.com/l/rtzyx",
				created: 1750143478,
				tags: [""],
			},
			{
				title: "Kabul Roundabout",
				price: 5,
				thumbnail: "afghanistan/Kabul_Roundabout.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/jwxnd",
				created: 1750143613,
				tags: [""],
			},
			{
				title: "Kabul Walls",
				price: 5,
				thumbnail: "afghanistan/Kabul_Walls.jpg",
				length: 6,
				link: "https://franklinvmoon.gumroad.com/l/pwlqe",
				created: 1750142955,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_1.jpg",
				length: 18,
				link: "https://franklinvmoon.gumroad.com/l/efmzeu",
				created: 1750143574,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 2",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_2.jpg",
				length: 5,
				link: "https://franklinvmoon.gumroad.com/l/flzob",
				created: 1750143374,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Buzkashi 3",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif_Buzkashi_Grounds_3.jpg",
				length: 11,
				link: "https://franklinvmoon.gumroad.com/l/zzdipq",
				created: 1750143442,
				tags: [""],
			},
			{
				title: "Mazar-e-Sharif Hazrat Ali",
				price: 5,
				thumbnail: "afghanistan/Mazar-e-Sharif_Hazrat_Ali.jpg",
				length: 9,
				link: "https://franklinvmoon.gumroad.com/l/qyoaoy",
				created: 1750143235,
				tags: [""],
			},
			{
				title: "Complete Afghanistan Collection (21 Clips)",
				price: 30,
				thumbnail: "afghanistan/afghanmain.jpg",
				link: "https://franklinvmoon.gumroad.com/l/kraynl",
				created: 1750143316,
				tags: [""],
				isPack: true,
			},
		],
		wallpapers: [
			"afghanistan_mazar-e-sharif_blue_mosque.jpg",
			"afghanistan_kabul_slums.jpg",
			"afghanistan_shot_humvee_mosque.jpg",
			"afghanistan_herat_mosque.jpg",
			"afghanistan_kabul_street.jpg",
			"afghanistan_snow.jpg",
			"afghanistan_bamyan_snow.jpg",
			"afghanistan_bamyan_buddha_hole.jpg",
			"afghanistan_bamyan_buddhas.jpg",
			"afghanistan_herat_mosque_2.jpg",
			"afghanistan_snowing.jpg",
			"afghanistan_horse_brawl.jpg",
			"afghanistan_baulk_walls.jpg",
			"afghanistan_TB_flag.jpg",
		],
	},
	// {
	// 	title: "Iran",
	// 	thumbnail: "iranmain.jpg",
	// 	hostedLink: "iran",
	// 	assetItemMetaData: [],
	// 	wallpapers: [],
	// },
];
