name: Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  test:
    name: Running Tests
    runs-on: ubuntu-latest

    steps:
      - name: Get Node...
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.0

      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Add Dependencies
        run: yarn

      - name: Run Tests
        run: yarn test
