name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  test:
    name: Lint, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Get Node...
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: "yarn"

      - name: Add Dependencies
        run: yarn

      - name: Lint
        run: yarn lint

      - name: Run Tests
        run: yarn test

      - name: Build
        run: yarn build
